### ISSUE TITLE
Multiple blockchains?

### ISSUE THREAD

**Issue by Entomy** [tomekw/simple_blockchain#1]
Is there good reason for blockchain being a type from which multiple instances can be created? Or does only one blockchain need to exist at a time. From my _limited_ understanding of them, a blockchain represents an entire transaction ledger, so I'm thinking only one needs to ever exist.

**Comment by tomekw** [comment]
Hmm, IMHO, if you treat blockchain as a poor man's database - not a currency - you can have multiple instances (database) in your application.

Makes sense?

**Comment by Entomy** [comment]
So then, would it make more sense for the blockchain to be an assignable type, or a state machine package?

**Comment by tomekw** [comment]
I would say it should be an assignable type.

**Comment by Entomy** [comment]
Block between different blockchains are compatible with each other?
